# Generated by Django 2.2.6 on 2019-12-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='name',
            new_name='company_name',
        ),
    ]
