# Generated by Django 2.2.6 on 2019-12-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0002_auto_20191204_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmodel',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='personsmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='person',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='person',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='project',
        ),
        migrations.DeleteModel(
            name='AccountsModel',
        ),
        migrations.DeleteModel(
            name='AssignmentModel',
        ),
        migrations.DeleteModel(
            name='CompanyModel',
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
        migrations.DeleteModel(
            name='PersonsModel',
        ),
        migrations.DeleteModel(
            name='ProjectsModel',
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
