# Generated by Django 2.2.6 on 2019-12-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0005_accountsmodel_assignmentmodel_customermodel_personsmodel_projectsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='name',
            new_name='customer_name',
        ),
    ]
