# Generated by Django 2.2.6 on 2019-12-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0008_auto_20191205_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.ProjectsModel'),
        ),
    ]
