# Generated by Django 2.2.6 on 2019-12-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0009_auto_20191205_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionModel',
        ),
    ]
